# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 21, 2, 47, 828018, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
